# Generated by Django 5.1 on 2024-09-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='Email Address',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='Instrument Type',
            new_name='Instrument_Type',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='Phone Number',
            new_name='Phone',
        ),
    ]
