# Generated by Django 5.1 on 2024-09-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='First Name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='Last Name',
            new_name='LastName',
        ),
    ]
