# Generated by Django 5.1 on 2024-09-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0002_rename_first_name_musician_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='LastName',
            new_name='Last_Name',
        ),
    ]
